### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by ttttonyhe** [lightbulb128/troy-nova#1]
Hello,

I'm wondering if this project's still work-in-progress since most of the tests are failing for me when I ran them with an A100 GPU.

Thank you!

**Comment by lightbulb128** [comment]
The HE schemes are fully implemented in this project and I expect them to work on all GPU environments with CUDA no less than 11.7. On my device with 4090, all 233 tests pass. It should work with A100 GPU, too. 

Could you attach more details on how the tests failed? If all tests with "Host" in them succeeded but those with "Device" fails, this could probably be a problem with the environment.

**Comment by lightbulb128** [comment]
I just tested the code with another machine with A100 and the tests are fine, with CUDA 12.4

![image](https://github.com/lightbulb128/troy-nova/assets/42494534/fb4a893a-171f-4409-a571-97992906f2f3)

**Comment by ttttonyhe** [comment]
Thank you for your reply, will give it a try and give feedback soon!

**Comment by ttttonyhe** [comment]
@lightbulb128 

You are right, all the tests with "Device" in them (109 tests) failed for me while all the other tests with "Host" in them (124 tests) succeeded.

My CUDA compiler version is `11.7` (also tried version `12.5`), architecture `native` (also tried `80`).

The failed tests all have the same error message:
```
unknown file: Failure
C++ exception with description "[MemoryPool::get] The singleton has been destroyed." thrown in the test body.
```

After turning off the `TROY_MEMORY_POOL` flag, all the tests passed.

**Comment by lightbulb128** [comment]
Curious. The memory pool aims to manage the GPU memory so that we can avoid frequently allocating and freeing them. If it is disabled, the GPU memory will be allocated/freed every time a ciphertext etc is constructed/deconstructed, which could slow down the program. I should look into this.

**Comment by lightbulb128** [comment]
I have added an unsafe implementation of MemoryPool which ignores premature destruction calling. You may try if it solves the problem by providing `TROY_MEMORY_POOL=ON` and `TROY_MEMORY_POOL_UNSAFE=ON` to your cmake options.

**Comment by ttttonyhe** [comment]
> I have added an unsafe implementation of MemoryPool which ignores premature destruction calling. You may try if it solves the problem by providing `TROY_MEMORY_POOL=ON` and `TROY_MEMORY_POOL_UNSAFE=ON` to your cmake options.

That solved it! All tests passed. 🎉
Thank you so much for your hard work.

**Comment by Creling** [comment]
Same problems here, the program will throw `"[MemoryPool::get] The singleton has been destroyed."` when `TROY_MEMORY_POOL_UNSAFE=OFF`.

```
Python 3.11.9
CMake  3.30.2
Nvidia Driver 545.23.08    
CUDA 12.3
RTX 3090
```

**Comment by lightbulb128** [comment]
Well, I am still not able to reproduce this. Would you run this and see if the same error appears?
```
#include "troy.h"

int main() {
    void* allocated = troy::MemoryPool::Allocate(1024);
    troy::MemoryPool::Free(allocated);
    troy::MemoryPool::Destroy();
    return 0;
}
```

**Comment by Creling** [comment]
Sure, I'll update this issue after I get out of the gym.

**Comment by Creling** [comment]
> Well, I am still not able to reproduce this. Would you run this and see if the same error appears?
> 
> ```
> #include "troy.h"
> 
> int main() {
>     void* allocated = troy::MemoryPool::Allocate(1024);
>     troy::MemoryPool::Free(allocated);
>     troy::MemoryPool::Destroy();
>     return 0;
> }
> ```

This snippet runs well without any error.

**Comment by lightbulb128** [comment]
I think this may be related to GoogleTest resetting the environment so the singleton is destroyed. If that is the case, you would see the unittests failing but all examples run normally.

**Comment by Creling** [comment]
I just propose a PR to fix it, please check it.

**Comment by lightbulb128** [comment]
Thanks for your hard work!

**Comment by lannnnn** [comment]
The same problem happened to me again, all the device tests failed.
I only test the c version, env:
CMake  3.30.5
CUDA 12.6
H100 
I tried different settings:
`TROY_MEMORY_POOL=ON and TROY_MEMORY_POOL_UNSAFE=ON`
and
`TROY_MEMORY_POOL=OFF`
But neither helped... even the quick start test failed when trying to run the troyexamples. The memory pool example give back the error shown as:

> Example for multiple devices with multiple memory pools.
> Device count = 3, thread count = 6.
> terminate called after throwing an instance of 'std::runtime_error'
> terminate called recursively
>   what():  [dyadic_product_ps] All inputs must be on the same device
> terminate called recursively
> Aborted

I have three GPU cards on the node where I test, I guess there should be something to fix in the code...
