### ISSUE TITLE
Python test failures

### ISSUE THREAD

**Issue by blossomin** [lightbulb128/troy-nova#13]
hello, I built this lib and tested the python. found many failures see the log file:
[test_results.log](https://github.com/user-attachments/files/17364660/test_results.log)

**Comment by lightbulb128** [comment]
Does the C++ side tests fail too?

**Comment by blossomin** [comment]
all the C++ tests passed

**Comment by lightbulb128** [comment]
Mostly the same for python interfaces. On C++/CUDA side the names are converted to snake_case from camelCase.

Yes my wx is lightbulb128.

**Comment by lightbulb128** [comment]
Python issue is a duplicate of #10. Solved by #14. Report if any further problems
