### ISSUE TITLE
Python Tests GeneralHeContext to_device_after_key_generation？

### ISSUE THREAD

**Issue by muyixi315** [lightbulb128/troy-nova#15]
pybind/tests/utils.py -> GeneralHeContext -> to_device_after_key_generation
```
if device and not to_device_after_key_generation:
            context.to_device_inplace()
            encoder.to_device_inplace()

if device and to_device_after_key_generation:
            context.to_device_inplace()
            encoder.to_device_inplace()
            key_generator.secret_key().to_device_inplace()
            encryptor.to_device_inplace()
            decryptor.to_device_inplace()
```
Hello! I would like to ask what is the role of the parameter "to_device_after_key_generation"? Is there an example where "True" is passed when GeneralHeContext is initialized?

**Comment by lightbulb128** [comment]
GeneralHeContext is a utility structure to ease my unit testing code writing, as it generalizes different semantics in CKKS, BFV and BGV, and "to_device_after_key_generation" is also for testing purposes. If handles when the context data are passed into device memory when the context is set up: 
* If false, we (1) create HeContext and Encoder, on host memory, (2) convey these to into device, (3) create KeyGenerator and all other utilities directly with device-memory HeContext and Encoder.
* If true, we (1) create HeContext, Encoder, KeyGenerator and all utilities on host memory, (2) convey all of them into device memory.

If you would like to use GenerenHeContext in your code, you could simply leave it as default, but both "true" and "false" should pose no actual difference to your later code of HE operations.
