### ISSUE TITLE
Is there any way to convert  Ciphertext to Cipher2d

### ISSUE THREAD

**Issue by gogogo66** [lightbulb128/troy-nova#3]
As  Cipher2d does not surpport multiply，I want to use a **Ciphertext** (r dims) to matmul **Plain2d** (r * n) to get a 1*n result，I tried to serialize the Ciphertext to bytes and then load it to Cipher2d, but it raise the error :

```
x_serialized = value.save(he) # value is the Ciphertext
x_encrypted = pytroy.Cipher2d.load_new(x_serialized, he)
```

> RuntimeError: [Ciphertext::load] Trying to call load with ciphertext with only terms saved.. 

I wonder is there any way to achieve this.

**Comment by lightbulb128** [comment]
The mechanics of Cipher2d loading and Ciphertext loading are implemented differently. You can treat the r-dims left-hand-side operand as a `1 x n` matrix. If `n` is small enough (to be exact, no larger than the polynomial modulus degree), the Cipher2d you get from this r-dim vector should effectively contain only one Ciphertext.

See  `examples/10_bfv_matmul` and `examples/11_ckks_matmul`.
