### ISSUE TITLE
Troy build失败

### ISSUE THREAD

**Issue by henshy** [lightbulb128/troy-nova#5]
代码是当前 master，用的显卡 A100，【cmake .. -DCMAKE_CUDA_ARCHITECTURES="80"】 构建成功，如下：
cmake .. -DCMAKE_CUDA_ARCHITECTURES="80"
-- The C compiler identification is GNU 9.3.1
-- The CXX compiler identification is GNU 9.3.1
-- The CUDA compiler identification is NVIDIA 11.0.221
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-9/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-9/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CUDA architectures: 80
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- pybind11 v2.11.1 
-- Found PythonInterp: /conda/envs/codelab/bin/python (found suitable version "3.6.10", minimum required is "3.6") 
-- Found PythonLibs: /home/*********************
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/*********

但在执行【make troy】时失败，试过cmake 3.18 和 cmake 3.30，都是这个问题，如下【粘贴了一部分，但都是和 uint128_t 相关】：
Scanning dependencies of target troy
[  2%] Building CUDA object src/CMakeFiles/troy.dir/app/bfv_ring2k.cu.o
*********/troy-nova/src/app/../utils/basics.h(580): error: "__uint128_t" is a 128-bit integer, which is not supported in device code

另外，请问如果用 py test 的话该步骤还是必需的吗？

**Comment by henshy** [comment]
我的 CUDA Version 是 11.4，不支持 128 bit，需要升级到 11.6 及以上才行，升级下再看看

**Comment by henshy** [comment]
build 成功，用的 v0.1.0，建议作者能把 CUDA version 的版本要求说明下

**Comment by lightbulb128** [comment]
在readme里面加了requirements。
