### ISSUE TITLE
Python 针对 Client-Server 模式的使用问题

### ISSUE THREAD

**Issue by henshy** [lightbulb128/troy-nova#6]
client 和 server 模式需要传递序列化的 Context 密钥，请问如何实现呢？看到 c++ 版本存储 publickey 和 secretkey 即可， python 的话直接把 context base64传递吗，但没看到可以 load context 的方法？

**Comment by henshy** [comment]
又看了下，实现方式是这样吗
 --  客户端和服务端创建相同参数的 EncryptionParameters，然后服务端加载客户端传输过来的 publickey 和 secretkey

**Comment by lightbulb128** [comment]
是，只要两方创建EncryptionParams使用的参数是一样的，创建的HeContext就会是一样的。
