### ISSUE TITLE
Symbol Lookup Error When Building with CUDA 12.5 and CMake 3.22

### ISSUE THREAD

**Issue by shashankballa** [lightbulb128/troy-nova#8]
I am encountering a symbol lookup error while building the project. Here are the details of my setup and the commands I am using:

- **Environment:**
  - Ubuntu 22.04
  - CUDA 12.5
  - CMake 3.22
  - g++ 11.4
  - gcc 11.4

- **Commands:**
  ```sh
  mkdir -p build && cd build && rm -rf *
  cmake .. -DCMAKE_CUDA_ARCHITECTURES=86 -DTROY_TEST=ON -DTROY_BENCH=ON -DTROY_EXAMPLES=ON -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON
  make clean && make -j16
  ```
  
I get this error from `make` in my last command:
  ```sh
  [100%] Linking CXX executable troytest
  /path/to/build/test/troytest: symbol lookup error: /path/to/build/test/troytest: undefined symbol: _ZN4troy5utils10MemoryPool11global_poolE
  CMake Error at /path/to/cmake/Modules/GoogleTestAddTests.cmake:83 (message):
    Error running test executable.
      Path: '/path/to/build/test/troytest'
      Result: 127
      Output:
  Call Stack (most recent call first):
    /path/to/cmake/Modules/GoogleTestAddTests.cmake:179 (gtest_discover_tests_impl)
  
  make[2]: *** [test/CMakeFiles/troytest.dir/build.make:502: test/troytest] Error 1
  make[2]: *** Deleting file 'test/troytest'
  make[1]: *** [CMakeFiles/Makefile2:1636: test/CMakeFiles/troytest.dir/all] Error 2
  make: *** [Makefile:136: all] Error 2
  ```
  
I would appreciate any guidance or suggestions to resolve this issue. Thank you! 🙏

**Comment by lightbulb128** [comment]
I wasn't able to reproduce this by running the commands you've given but I got a similar result when I removed `./build/src/libtroy.so` and then running ctest in `./build/test`. So I suppose this is about your executable not finding the dynamic library.

You could probably track down this by
1. `make troytest`, `ldd test/troytest` . The output should contain a line that points to a `libtroy.so`, and it should be `./build/src/libtroy.so`.
2. See if `libtroy.so` is there. If not, try to build it with `make troy`.

**Comment by lightbulb128** [comment]
FYI, if you get a `libtroy.so`, you can list its symbols by `nm -D libtroy.so` and see if the missing symbol is there. For example, my `nm -D libtroy.so | grep global` gives
```
00000000004804d0 B _ZN4troy5utils10MemoryPool11global_poolE
00000000004804a0 B _ZN4troy5utils10MemoryPool17global_pool_mutexE
```

**Comment by shashankballa** [comment]
I do have `_ZN4troy5utils10MemoryPool11global_poolE` in `./build/src/libtroy.so`. I think the issue comes from an incorrect compile time linker to this object file, causing the compiler to either miss this object file or, perhaps, a different one situated at some other location

**Comment by shashankballa** [comment]
I was able to fix the issue by linking to `troy_static` instead of `troy` in the `CMakeList.txt` files of the `examples` and `test` directories.

BTW I spotted a small error in lines 46, 47, 53, and 57 of [`/test/bench/ntt.cu`](https://github.com/lightbulb128/troy-nova/blob/c89a8980c2b266d9fe82f69b03f52b62abaecf5f/test/bench/ntt.cu#L46). Aren't these instructions supposed to  "in-place" ones?

**Comment by lightbulb128** [comment]
Yes, those should be "ntt_inplace" and "intt_inplace". will update this bench_ntt in a recent update.
